server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///test  # 这里为什么是这样的格式？
    username: root
    password: sasa
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-provider # 将来也会作为微服务的名称
mybatis:
  type-aliases-package: cn.nw.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka